/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 43GLDCvnvwFaSntiZWsgtz
// Component: scyO_hkhBT6w

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import StudentPageLayout from "../../StudentPageLayout"; // plasmic-import: Itd9tHC_WCDz/component
import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import Button from "../../Button"; // plasmic-import: jI-x_NzEFX2Q/component
import CourseCard from "../../CourseCard"; // plasmic-import: lU_2619e8-pr/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 43GLDCvnvwFaSntiZWsgtz/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 43GLDCvnvwFaSntiZWsgtz/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 43GLDCvnvwFaSntiZWsgtz/projectcss
import sty from "./PlasmicStudentCourses.module.css"; // plasmic-import: scyO_hkhBT6w/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: yZz0P1JDPQwS/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: -jkcn7GwAM4v/icon

createPlasmicElementProxy;

export type PlasmicStudentCourses__VariantMembers = {};
export type PlasmicStudentCourses__VariantsArgs = {};
type VariantPropType = keyof PlasmicStudentCourses__VariantsArgs;
export const PlasmicStudentCourses__VariantProps = new Array<VariantPropType>();

export type PlasmicStudentCourses__ArgsType = {};
type ArgPropType = keyof PlasmicStudentCourses__ArgsType;
export const PlasmicStudentCourses__ArgProps = new Array<ArgPropType>();

export type PlasmicStudentCourses__OverridesType = {
  root?: Flex__<typeof StudentPageLayout>;
};

export interface DefaultStudentCoursesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStudentCourses__RenderFunc(props: {
  variants: PlasmicStudentCourses__VariantsArgs;
  args: PlasmicStudentCourses__ArgsType;
  overrides: PlasmicStudentCourses__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <StudentPageLayout
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames("__wab_instance", sty.root)}
        >
          <DataCtxReader__>
            {$ctx => (
              <div className={classNames(projectcss.all, sty.freeBox__gyCy)}>
                <div className={classNames(projectcss.all, sty.freeBox__aOrVu)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qyl9C)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__mvDd0
                      )}
                    >
                      {"My Courses (30)"}
                    </h4>
                    <AntdDropdown
                      className={classNames(
                        "__wab_instance",
                        sty.dropdown__p02L1
                      )}
                      dropdownMenuScopeClassName={
                        sty["dropdown__p02L1__dropdownMenu"]
                      }
                      menuItems={() => (
                        <React.Fragment>
                          <AntdMenuItem
                            className={classNames(
                              "__wab_instance",
                              sty.menuItem__j5Gv2
                            )}
                            key={"menu-item-1"}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__cjpLq
                              )}
                            >
                              {"Menu item"}
                            </div>
                          </AntdMenuItem>
                          <AntdMenuItem
                            className={classNames(
                              "__wab_instance",
                              sty.menuItem__q4W0O
                            )}
                            key={"menu-item-2"}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jx1Lt
                              )}
                            >
                              {"Menu item"}
                            </div>
                          </AntdMenuItem>
                        </React.Fragment>
                      )}
                      menuItemsJson={[
                        { type: "item", value: "action1", label: "Action 1" },
                        { type: "item", value: "action2", label: "Action 2" }
                      ]}
                    >
                      <AntdButton
                        className={classNames(
                          "__wab_instance",
                          sty.button__udcwn
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lAiv4
                          )}
                        >
                          {"Dropdown"}
                        </div>
                      </AntdButton>
                    </AntdDropdown>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__aSnNz
                      )}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.columns__uv5To)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__dyr4U)}
                    >
                      <CourseCard
                        className={classNames(
                          "__wab_instance",
                          sty.courseCard___6BUkT
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__iEcyc)}
                    >
                      <CourseCard
                        className={classNames(
                          "__wab_instance",
                          sty.courseCard___4Mbtk
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___0F7C)}
                    >
                      <CourseCard
                        className={classNames(
                          "__wab_instance",
                          sty.courseCard___2IaFo
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__kcBuJ)}
                    >
                      <CourseCard
                        className={classNames(
                          "__wab_instance",
                          sty.courseCard__xt9Js
                        )}
                      />
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__w2W1D)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cLo8Z)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__z84Zp
                      )}
                    >
                      {"More Courses (30)"}
                    </h4>
                    <AntdDropdown
                      className={classNames(
                        "__wab_instance",
                        sty.dropdown___3Wzt
                      )}
                      dropdownMenuScopeClassName={
                        sty["dropdown___3Wzt__dropdownMenu"]
                      }
                      menuItems={() => (
                        <React.Fragment>
                          <AntdMenuItem
                            className={classNames(
                              "__wab_instance",
                              sty.menuItem__efAil
                            )}
                            key={"menu-item-1"}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__mJy6U
                              )}
                            >
                              {"Menu item"}
                            </div>
                          </AntdMenuItem>
                          <AntdMenuItem
                            className={classNames(
                              "__wab_instance",
                              sty.menuItem__pMvfh
                            )}
                            key={"menu-item-2"}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__koah6
                              )}
                            >
                              {"Menu item"}
                            </div>
                          </AntdMenuItem>
                        </React.Fragment>
                      )}
                      menuItemsJson={[
                        { type: "item", value: "action1", label: "Action 1" },
                        { type: "item", value: "action2", label: "Action 2" }
                      ]}
                    >
                      <AntdButton
                        className={classNames(
                          "__wab_instance",
                          sty.button__pfZtj
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9Xbm
                          )}
                        >
                          {"Dropdown"}
                        </div>
                      </AntdButton>
                    </AntdDropdown>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__tsN2X
                      )}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.columns__d1EJs)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__eWNhj)}
                    >
                      <CourseCard
                        className={classNames(
                          "__wab_instance",
                          sty.courseCard__swOX
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__nuJxM)}
                    >
                      <CourseCard
                        className={classNames(
                          "__wab_instance",
                          sty.courseCard__r3Yr5
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___0VWw2)}
                    >
                      <CourseCard
                        className={classNames(
                          "__wab_instance",
                          sty.courseCard__uRdbt
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__g5TJd)}
                    >
                      <CourseCard
                        className={classNames(
                          "__wab_instance",
                          sty.courseCard__inaC
                        )}
                      />
                    </div>
                  </div>
                </div>
              </div>
            )}
          </DataCtxReader__>
        </StudentPageLayout>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof StudentPageLayout;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStudentCourses__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStudentCourses__VariantsArgs;
    args?: PlasmicStudentCourses__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStudentCourses__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicStudentCourses__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStudentCourses__ArgProps,
          internalVariantPropNames: PlasmicStudentCourses__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStudentCourses__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStudentCourses";
  } else {
    func.displayName = `PlasmicStudentCourses.${nodeName}`;
  }
  return func;
}

export const PlasmicStudentCourses = Object.assign(
  // Top-level PlasmicStudentCourses renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicStudentCourses
    internalVariantProps: PlasmicStudentCourses__VariantProps,
    internalArgProps: PlasmicStudentCourses__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicStudentCourses;
/* prettier-ignore-end */
